config/routes.rb
Do::Application.routes.draw do
  resources :homeworks
  resources :messages

  resources :assignments do
    get :assign, :on => :member 
    get :puto, :on => :member
    get :already, :on => :member
    get :putout, :on => :member
  end
  resources :depots do
    get :part_list, :on => :member
  end
  resources :categories

  controller :sessions do
    get 'login' => :new
    root :to => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  get '/register' => "users#new"
  get 'registered' => "users#registered"
  match 'user_info' => "users#info"
  get 'user_act' => "users#user_act"
  resources :users
  match 'circles/search' => 'circles#search'
  match 'depots/search' => 'depots#search'
  match 'circles_join_me' => 'circles#join_me'
  match 'add_friend' => 'circles#add_friend'
  resources :circles do
    get :part_list, :on => :member
  end

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  attr_accessible :category_id, :circle_id, :discription, :invalidate, :timelimit, :title, :typies, :user_id, :validate,:valitime, :add_homework, :del_homework
  validates_presence_of :title
  belongs_to :user
  # attr_accessor :validate_date, :validate_time
  # after_initialize :get_validate
  # before_validation :set_validate

  # def get_validate
  #  self.validate ||= Time.now
  #  self.validate_date ||= self.validate.to_date.to_s(:db)
  #  self.validate_time ||= "#{'%02d' % self.validate.hour}:#{'%02d' % self.validate.min}"
  # end
  # def set_validate
  #  self.validate = "#{self.validate_date} #{self.validate_time}:00"
  # end
  def valitime
    mu = 0
    unless validate.blank? and invalidate.blank?
      mu = (self.invalidate - self.validate)/60
    end
    mu
  end
  def valitime=(value)
    self.invalidate = self.validate + value.to_i*60
  end
  def add_homework(value)
    if self.homework.blank?
      self.homework = value
    else
      a = self.homework.split(",").map{|s| s.to_i} << value.to_i
      self.homework = a.join(",")
    end
  end
  def del_homework(value)
    unless self.homework.blank?
      a = self.homework.split(",").map{|s| s.to_i}
      a.delete(value.to_i)
      self.homework = a.join(",")
    end

  end
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  # GET /assignments
  # GET /assignments.json
  def index
    @assignments = current_user.assignments.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @assignments }
    end
  end

  # GET /assignments/1
  # GET /assignments/1.json
  def show
    @assignment = Assignment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @assignment }
    end
  end

  # GET /assignments/new
  # GET /assignments/new.json
  def new
    @assignment = Assignment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @assignment }
    end
  end

  # GET /assignments/1/edit
  def edit
    @assignment = Assignment.find(params[:id])
  end

  # POST /assignments
  # POST /assignments.json
  def create
    @assignment = Assignment.new(params[:assignment])

    respond_to do |format|
      if @assignment.save
        format.html { redirect_to @assignment, notice: 'Assignment was successfully created.' }
        format.json { render json: @assignment, status: :created, location: @assignment }
      else
        format.html { render action: "new" }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /assignments/1
  # PUT /assignments/1.json
  def update
    @assignment = Assignment.find(params[:id])

    respond_to do |format|
      if @assignment.update_attributes(params[:assignment])
        format.html { redirect_to @assignment, notice: 'Assignment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assignments/1
  # DELETE /assignments/1.json
  def destroy
    @assignment = Assignment.find(params[:id])
    @assignment.destroy

    respond_to do |format|
      format.html { redirect_to assignments_url }
      format.json { head :no_content }
    end
  end
  def assign
    @assignment = Assignment.find(params[:id])
    unless @assignment.homework.blank?
    d = @assignment.homework.split(",").map { |s| s.to_i }
      @depots = @assignment.user.depots.where("id not in (?)",d)
    else
      @depots = @assignment.user.depots.all
    end
    respond_to do |format|
      format.js
    end
  end
  def puto
    @assignment = Assignment.find(params[:assignment])
    @assignment.add_homework(params[:depot])
    @depot = params[:depot]
    @assignment.save
    respond_to do |format|
      format.js
    end
  end
  def already
    @assignment = Assignment.find(params[:id])
    if @assignment.homework
    d = @assignment.homework.split(",").map { |s| s.to_i }
    @depots = @assignment.user.depots.where("id in (?)", d)
    else
    @depots = @assignment.user.depots.where("id in (?)", nil)
    end
    respond_to do |format|
      format.js
    end
  end
  def putout
    @assignment = Assignment.find(params[:assignment])
    @assignment.del_homework(params[:depot])
    @depot = params[:depot]
    @assignment.save
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/assignments/_form.html.erb
<%= form_for(@assignment,:html => {:class => "form-horizontal"}) do |f| %>
  <% if @assignment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@assignment.errors.count, "error") %> prohibited this assignment from being saved:</h2>

      <ul>
        <% @assignment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset><legend>布置新作业</legend>
    <div class="control-group">
      <label class="control-label" for="assignment_title">标题</label>
      <div class="controls">
        <%= f.text_field :title %>
      </div>
    </div>
    <%= f.hidden_field :user_id,:value => current_user.id %>
    <div class="control-group">
      <label class="control-label" for="assignment_circle">圈子</label>
      <div class="controls">
        <%= f.select :circle_id, current_user.circles.all.map{|c| [c.title,c.id]}.unshift(["暂不圈人",0]) %>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label">开始时间</label>
      <div class="controls">
        <%= f.hidden_field :typies,:value => "homework" %>
        <%= f.hidden_field :user_id, :value => current_user.id %>
        <%= f.hidden_field :timelimit,:value => 0 %>
        <div class="input-append date" id="validate">
        <%= f.text_field :validate %>
        <span class="add-on">
          <i data-time-icon="icon-time" data-date-icon="icon-calendar"></i>
        </span>
      </div>
      </div>
    </div>
    <div class="control-group">
      <label class = "control-label">有效时间（分钟）</label>
      <div class="controls">
          <%= f.text_field :valitime %>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label">说明</label>
      <div class="controls">
        <%= f.text_area :discription, :rows => 3 %>
      </div>
    </div>
    <div class="control-group">
      <div class="controls">
        <div class="actions">
          <%= f.submit %>
    </div></div></div>
  </fieldset>
<% end %>
<script type="text/javascript">
  $(function(){
      $("#validate>input").datetimepicker({
        language: 'zh-CN'
      });
      $("#invalidate>input").datetimepicker({
        language: 'zh-CN'
     });
  });
    </script>

app/views/assignments/_par_already.html.erb
已有题目
<% @depots.each do |depot| %>
  <div class="media" id="dep_<%= depot.id %>">
    <div class="pull-left">
    </div>
    <div class="media-body">
      <h4 class="media-heading">
      <%= depot.title %>
    </h4>
    <%= link_to "移除", putout_assignment_path(:depot=>depot,:assignment=>@assignment), :class=>"btn", :remote => true %>
  </div>
</div>
<% end %>

app/views/assignments/_par_assign.html.erb
添加新题目

app/views/assignments/_sidebar.html.erb
<h3> Sidebar </h3>

app/views/assignments/already.js.erb
$("#list").html("<%=j render 'par_already' %>").hide().show(1000);

app/views/assignments/assign.js.erb
$("#list").html("<%=j render 'par_assign' %>").hide().show(1000);

app/views/assignments/edit.html.erb
<h1>Editing assignment</h1>

<%= render 'form' %>

<%= link_to 'Show', @assignment %> |
<%= link_to 'Back', assignments_path %>

app/views/assignments/index.html.erb
<%= render 'depots/navbar' %>
<h1>Listing assignments</h1>

<% @assignments.each do |assignment| %>
  <div class="media">
    <a class="pull-left" href="#">
      <img class="media-object" data-src="holder.js/64x64">
    </a>
    <div class="media-body">
      <h4 class="media-heading">
        <%= assignment.title %>
      </h4>
    <%= assignment.circle_id %>，
    <span class="label label-success"><%= DateTime.parse(assignment.validate.to_s).strftime("%Y年%m月%d日%H时%M分").to_s %>生效</span>
    <span class="label label-important"> <%= datetime_to_cn assignment.invalidate %>结束</span><br />
    <p><%= assignment.discription %></p>
    <div>
    <%= link_to 'Show', assignment,:class=>"btn" %>
    <%= link_to 'Edit', edit_assignment_path(assignment),:class=>"btn" %>
    <%= link_to 'Destroy', assignment, method: :delete, data: { confirm: 'Are you sure?'},:class=>"btn" %>
  </div>
  </div>
</div>
<% end %>

app/views/assignments/new.html.erb
<h1>New assignment</h1>

<%= render 'form' %>

<%= link_to 'Back', assignments_path %>

app/views/assignments/puto.js.erb
$("#dep_<%= @depot %>").hide(1000);

app/views/assignments/putout.js.erb
$("#dep_<%= @depot %>").hide(1000);

app/views/assignments/show.html.erb
<p id="notice"><%= notice %></p>

<h4>Listing assignments</h4>

  <div class="media">
    <a class="pull-left" href="#">
      <img class="media-object" data-src="holder.js/64x64">
    </a>
    <div class="media-body">
      <h4 class="media-heading">
        <%= @assignment.title %>
      </h4>
    <%= @assignment.circle_id %>，
    <span class="label label-success"><%= DateTime.parse(@assignment.validate.to_s).strftime("%Y年%m月%d日%H时%M分").to_s %>生效</span>
    <span class="label label-important"> <%= datetime_to_cn @assignment.invalidate %>结束</span><br />
    <p><%= @assignment.discription %></p>
    <div>
    <%= link_to 'Show', @assignment,:class=>"btn" %>
    <%= link_to 'Edit', edit_assignment_path(@assignment),:class=>"btn" %>
    <%= link_to 'Destroy', @assignment, method: :delete, data: { confirm: 'Are you sure?'},:class=>"btn" %>
    <%= link_to '已有题目', already_assignment_path(@assignment), :class => "btn", :remote => true %>
    <%= link_to '添加题目', assign_assignment_path(@assignment), :class => "btn",:remote => true %>
  </div>
  </div>
</div>
<div id="list">
</div>