config/routes.rb
Do::Application.routes.draw do
  resources :homeworks
  resources :messages

  resources :assignments do
    get :assign, :on => :member 
    get :puto, :on => :member
    get :already, :on => :member
    get :putout, :on => :member
  end
  resources :depots do
    get :part_list, :on => :member
  end
  resources :categories

  controller :sessions do
    get 'login' => :new
    root :to => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  get '/register' => "users#new"
  get 'registered' => "users#registered"
  match 'user_info' => "users#info"
  get 'user_act' => "users#user_act"
  resources :users
  match 'circles/search' => 'circles#search'
  match 'depots/search' => 'depots#search'
  match 'circles_join_me' => 'circles#join_me'
  match 'add_friend' => 'circles#add_friend'
  resources :circles do
    get :part_list, :on => :member
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :title, :parent_id, :discription, :user_id
  validates_presence_of :title, :message => "Title can't be nill"
  validates_presence_of :user_id
  belongs_to :user
  has_many :depots
  has_ancestry
  def self.arrange_as_array(options = {}, hash = nil)
    hash ||= arrange(options)
    arr = []
    hash.each do |node, children|
      arr << node
      arr += arrange_as_array(options, children) unless children.empty?
    end
    arr
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = current_user.categories

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = current_user.categories.new
    @categories = current_user.categories.all.each { |c| c.ancestry = c.ancestry.to_s + (c.ancestry != nil ? "/" : '') + c.id.to_s}.sort {|x,y| x.ancestry <=> y.ancestry}.map{ |c| ["->" * (c.depth - 1) + c.title,c.id] }.unshift(["-- none --", nil])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
    @categories = current_user.categories.all.each { |c| c.ancestry = c.ancestry.to_s + (c.ancestry != nil ? "/" : '') + c.id.to_s}.sort {|x,y| x.ancestry <=> y.ancestry}.map{ |c| ["->" * (c.depth - 1) + c.title,c.id] }.unshift(["-- none --", nil])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])
    
    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category,:html=>{:class=>"form-horizontal"}) do |f| %>
  <%= f.hidden_field :user_id %>
  <fieldset>
    <legend>Create New Category</legend>
    <% if @category.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

        <ul>
          <% @category.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="control-group">
      <label class="control-label" for="category_title">Category Title</label>
      <div class="controls">
        <%= f.text_field :title, :id => "category_title" %>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="category_parent_id">Super Category</label>
      <div class="controls">
        <%= f.select :parent_id, @categories %>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="category_discription">Discription</label>
      <div class="controls">
        <%= f.text_area :discription, :rows=>3 %>
      </div>
    </div>
    <div class="control-group">
      <div class="controls">
        <%= f.submit "添加", :class=>"btn" %>
    </div>
  </div>
    </fieldset>
  <% end %>

app/views/categories/_sidebar.html.erb
sidebar
<div class="btn-group btn-group-vertical">
 <a href="" class="btn">add new</a>
 <a href="" class="btn">edit a</a>
 <a href="" class="btn">list all</a>
 <a href="" class="btn">a</a>
 <a href="" class="btn">a</a>
</div>

app/views/categories/_submenu.html.erb
<div class="btn-group">
  <a href="" class="btn"></a>
  <a href="" class="btn"></a>
  <a href="" class="btn"></a>
  <a href="" class="btn"></a>
</div>

app/views/categories/edit.html.erb
<%= form_for(@category,:html=>{:class=>"form-horizontal"}) do |f| %>
  <%= f.hidden_field :user_id %>
  <fieldset>
    <legend>编辑分类</legend>
    <% if @category.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

        <ul>
          <% @category.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="control-group">
      <label class="control-label" for="category_title">Category Title</label>
      <div class="controls">
        <%= f.text_field :title, :id => "category_title" %>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="category_parent_id">Super Category</label>
      <div class="controls">
        <%= f.select :parent_id, @categories %>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="category_discription">Discription</label>
      <div class="controls">
        <%= f.text_area :discription, :rows=>3 %>
      </div>
    </div>
    <div class="control-group">
      <div class="controls">
        <%= f.submit "更新", :class=>"btn" %>
    </div>
  </div>
    </fieldset>
  <% end %>

app/views/categories/index.html.erb
<h3>分类列表</h3>

<% @categories.arrange_as_array.each do |category| %>
  <div class="span8 offset<%= category.depth %>">
    <div class="btn-toolbar">
      <div class="btn-group">
        <button class="btn"><%= category.title %></button>
        <%= link_to "编辑", edit_category_path(category), :class => "btn" %>
        <%= link_to 'Remove', category_path(category), :method => :delete, :class => "btn" %>
      </div>
    </div>
  </div>
<% end %>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>