config/routes.rb
Do::Application.routes.draw do
  resources :homeworks
  resources :messages

  resources :assignments do
    get :assign, :on => :member 
    get :puto, :on => :member
    get :already, :on => :member
    get :putout, :on => :member
  end
  resources :depots do
    get :part_list, :on => :member
  end
  resources :categories

  controller :sessions do
    get 'login' => :new
    root :to => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  get '/register' => "users#new"
  get 'registered' => "users#registered"
  match 'user_info' => "users#info"
  get 'user_act' => "users#user_act"
  resources :users
  match 'circles/search' => 'circles#search'
  match 'depots/search' => 'depots#search'
  match 'circles_join_me' => 'circles#join_me'
  match 'add_friend' => 'circles#add_friend'
  resources :circles do
    get :part_list, :on => :member
  end

end

app/models/depot.rb
class Depot < ActiveRecord::Base
  attr_accessible :owner_id, :user_id, :title, :category_id, :typies, :item_a, :item_b, :item_c, :item_d, :item_e, :item_f, :item_g, :item_h, :item_i, :item_j, :keys, :key_a, :key_b, :key_c, :key_d, :key_e, :key_f, :key_g, :key_h, :key_i, :key_j, :readspeed
  belongs_to :user, :foreign_key => "owner_id"
  belongs_to :category
  before_save :move_empty

  def key_a
    v = ""
    unless self.keys.blank?
      if self.keys.include??A
        v = "A"
      end
    end
    v
  end

  def key_a=(v)
    if v == "A"
      if self.keys.blank?
        self.keys = "A"
      else
        unless self.keys.include??A
          self.keys += "A"
        end
      end
    else
      self.keys = self.keys.delete "A" unless self.keys.blank?
    end
  end

  def key_b
    v = ""
    unless self.keys.blank?
      if self.keys.include??B
        v = "B"
      end
    end
    v
  end

  def key_b=(v)
    if v == "B"
      if self.keys.blank?
        self.keys = "B"
      else
        unless self.keys.include??B
          self.keys += "B"
        end
      end
    else
      self.keys = self.keys.delete "B" unless self.keys.blank?
    end
  end

  def key_c
    v = ""
    unless self.keys.blank?
      if self.keys.include??C
        v = "C"
      end
    end
    v
  end

  def key_c=(v)
    if v == "C"
      if self.keys.blank?
        self.keys = "C"
      else
        unless self.keys.include??C
          self.keys += "C"
        end
      end
    else
      self.keys = self.keys.delete "C" unless self.keys.blank?
    end
  end

  def key_d
    v = ""
    unless self.keys.blank?
      if self.keys.include??D
        v = "D"
      end
    end
    v
  end

  def key_d=(v)
    if v == "D"
      if self.keys.blank?
        self.keys = "D"
      else
        unless self.keys.include??D
          self.keys += "D"
        end
      end
    else
      self.keys = self.keys.delete "D" unless self.keys.blank?
    end
  end

  def key_e
    v = ""
    unless self.keys.blank?
      if self.keys.include??E
        v = "E"
      end
    end
    v
  end

  def key_e=(v)
    if v == "E"
      if self.keys.blank?
        self.keys = "E"
      else
        unless self.keys.include??E
          self.keys += "E"
        end
      end
    else
      self.keys = self.keys.delete "E" unless self.keys.blank?
    end
  end

  def key_f
    v = ""
    unless self.keys.blank?
      if self.keys.include??F
        v = "F"
      end
    end
    v
  end

  def key_f=(v)
    if v == "F"
      if self.keys.blank?
        self.keys = "F"
      else
        unless self.keys.include??F
          self.keys += "F"
        end
      end
    else
      self.keys = self.keys.delete "F" unless self.keys.blank?
    end
  end

  def key_g
    v = ""
    unless self.keys.blank?
      if self.keys.include??G
        v = "G"
      end
    end
    v
  end

  def key_g=(v)
    if v == "G"
      if self.keys.blank?
        self.keys = "G"
      else
        unless self.keys.include??G
          self.keys += "G"
        end
      end
    else
      self.keys = self.keys.delete "G" unless self.keys.blank?
    end
  end

  def key_h
    v = ""
    unless self.keys.blank?
      if self.keys.include??H
        v = "H"
      end
    end
    v
  end

  def key_h=(v)
    if v == "H"
      if self.keys.blank?
        self.keys = "H"
      else
        unless self.keys.include??H
          self.keys += "H"
        end
      end
    else
      self.keys = self.keys.delete "H" unless self.keys.blank?
    end
  end

  def key_i
    v = ""
    unless self.keys.blank?
      if self.keys.include??I
        v = "I"
      end
    end
    v
  end

  def key_i=(v)
    if v == "I"
      if self.keys.blank?
        self.keys = "I"
      else
        unless self.keys.include??I
          self.keys += "I"
        end
      end
      self.keys = self.keys.delete "I" unless self.keys.blank?
    end
  end

  def key_j
    v = ""
    unless self.keys.blank?
      if self.keys.include??J
        v = "J"
      end
    end
    v
  end

  def key_j=(v)
    if v == "J"
      if self.keys.blank?
        self.keys = "J"
      else
        unless self.keys.include??J
          self.keys += "J"
        end
      end
      self.keys = self.keys.delete "J" unless self.keys.blank?
    end
  end

  protected
  def move_empty
    if self.typies == "single" or self.typies == "multiple"
      unless self.keys.blank?
        self.keys = self.keys.delete "T"
        self.keys = self.keys.delete "L"
      end
      (1..9).each do
        if self.item_a.blank? and !self.item_b.blank?
          self.item_a = self.item_b
          if self.keys.include??B
            self.keys += "A" unless self.keys.include??A
            self.keys.delete "B"
          end
          self.item_b = nil
        end
        if self.item_b.blank? and !self.item_c.blank?
          self.item_b = self.item_c
          if self.keys.include??C
            self.keys += "B" unless self.keys.include??B
            self.keys.delete "C"
          end
          self.item_c = nil
        end
        if self.item_c.blank? and !self.item_d.blank?
          self.item_c = self.item_d
          if self.keys.include??D
            self.keys += "C" unless self.keys.include??C
            self.keys.delete "D"
          end
          self.item_d = nil
        end
        if self.item_d.blank? and !self.item_e.blank?
          self.item_d = self.item_e
          if self.keys.include??E
            self.keys += "D" unless self.keys.include??D
            self.keys.delete "E"
          end
          self.item_e = nil
        end
        if self.item_e.blank? and !self.item_f.blank?
          self.item_e = self.item_f
          if self.keys.include??F
            self.keys += "E" unless self.keys.include??E
            self.keys.delete "F"
          end
          self.item_f = nil
        end
        if self.item_f.blank? and !self.item_g.blank?
          self.item_f = self.item_g
          if self.keys.include??G
            self.keys += "F" unless self.keys.include??F
            self.keys.delete "G"
          end
          self.item_g = nil
        end
        if self.item_g.blank? and !self.item_h.blank?
          self.item_g = self.item_h
          if self.keys.include??H
            self.keys += "G" unless self.keys.include??G
            self.keys.delete "H"
          end
          self.item_h = nil
        end
        if self.item_h.blank? and !self.item_i.blank?
          self.item_h = self.item_i
          if self.keys.include??I
            self.keys += "H" unless self.keys.include??H
            self.keys.delete "I"
          end
          self.item_i = nil
        end
        if self.item_i.blank? and !self.item_j.blank?
          self.item_i = self.item_j
          if self.keys.include??J
            self.keys += "I" unless self.keys.include??I
            self.keys.delete "J"
          end
          self.item_j = nil
        end
      end
    elsif self.typies == "judgment"
      unless self.keys.blank?
        ("A".."J").each do |c|
          self.keys = self.keys.delete c
        end
      end
    end
  end
end

app/controllers/depots_controller.rb
class DepotsController < ApplicationController
  # GET /depots
  # GET /depots.json
  def index
    @depots = current_user.depots.order("id desc")
    flash[:notice] = "You are no any depot" if @depots.blank?

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @depots }
    end
  end

  # GET /depots/1
  # GET /depots/1.json
  def show
    @depot = Depot.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @depot }
    end
  end

  # GET /depots/new
  # GET /depots/new.json
  def new
    @depot = Depot.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @depot }
    end
  end

  # GET /depots/1/edit
  def edit
    @depot = Depot.find(params[:id])
  end

  # POST /depots
  # POST /depots.json
  def create
    @depot = Depot.new(params[:depot])

    respond_to do |format|
      if @depot.save
        format.html { redirect_to @depot, notice: 'Depot was successfully created.' }
        format.json { render json: @depot, status: :created, location: @depot }
      else
        format.html { render action: "new" }
        format.json { render json: @depot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /depots/1
  # PUT /depots/1.json
  def update
    @depot = Depot.find(params[:id])

    respond_to do |format|
      if @depot.update_attributes(params[:depot])
        format.html { redirect_to @depot, notice: 'Depot was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @depot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /depots/1
  # DELETE /depots/1.json
  def destroy
    @depot = Depot.find(params[:id])
    @depot.destroy

    respond_to do |format|
      format.html { redirect_to depots_url }
      format.json { head :no_content }
    end
  end
  def search

  end
end

app/helpers/depots_helper.rb
# encoding: utf-8
module DepotsHelper
  def read_speed
    [["中等速度［每秒5字］",5],["无需思考［每秒6字］",6],["需要思考［每秒4字］",4],["需要计算［每秒3字］",3]]
  end
end

app/views/depots/_edit_judge.html.erb
# encoding: utf-8
<div class="control-group">
  <label class="control-label">答案</label>
  <div class="controls"><div class="form-inline">
    <%= f.radio_button :keys, "T" %><label for="depot_keys_t">正确</label>
    <%= f.radio_button :keys, "L" %><label for="depot_keys_f">错误</label>
  </div>
</div>
</div>

app/views/depots/_edit_much.html.erb
<div id="option_a">
  <div class="control-group">
    <label class="control-label">A</label>
    <div class="controls">
      <%= f.text_area :item_a, :rows => 3%>
      <%= f.check_box :key_a, {:id => "depot_keys_a"}, "A","" %>
    </div>
  </div>
  <div class="control-group" id="btn_con_a">
    <div class="controls">
      <button class="btn" type="button" id="btn_add_b">Add B</button>
    </div>
  </div>
</div>
<div id="option_b">
  <div class="control-group">
    <label class="control-label">B</label>

    <div class="controls">
      <%= f.text_area :item_b, :rows => 3 %>
      <%= f.check_box :key_b, {:id => "depot_keys_b"}, "B", "" %>
    </div>
  </div>
  <div class="control-group" id="btn_con_b">
    <div class="controls">
      <div class="btn-group">
        <button class="btn" type="button" id="btn_add_c">Add C</button>
        <button class="btn" type="button" id="btn_del_b">delete B</button>
      </div>
    </div>
  </div>
</div>
<div id="option_c">
  <div class="control-group">
    <label class="control-label">C</label>

    <div class="controls">
      <%= f.text_area :item_c, :rows => 3 %>
      <%= f.check_box :key_c, {:id => "depot_keys_c"}, "C", "" %>
    </div>
  </div>
  <div class="control-group" id="btn_con_c">
    <div class="controls">
      <div class="btn-group">
        <button class="btn" type="button" id="btn_add_d">Add D</button>
        <button class="btn" type="button" id="btn_del_c">delete C</button>
      </div>
    </div>
  </div>
</div>
<div id="option_d">
  <div class="control-group">
    <label class="control-label">D</label>

    <div class="controls">
      <%= f.text_area :item_d, :rows => 3 %>
      <%= f.check_box :key_d, {:id => "depot_keys_d"}, "D", "" %>
    </div>
  </div>
  <div class="control-group" id="btn_con_d">
    <div class="controls">
      <div class="btn-group">
        <button class="btn" type="button" id="btn_add_e">Add E</button>
        <button class="btn" type="button" id="btn_del_d">delete D</button>
      </div>
    </div>
  </div>
</div>
<div id="option_e">
  <div class="control-group">
    <label class="control-label">E</label>

    <div class="controls">
      <%= f.text_area :item_e, :rows => 3 %>
      <%= f.check_box :key_e, {:id => "depot_keys_e"}, "E", "" %>
    </div>
  </div>
  <div class="control-group" id="btn_con_e">
    <div class="controls">
      <div class="btn-group">
        <button class="btn" type="button" id="btn_add_f">Add F</button>
        <button class="btn" type="button" id="btn_del_e">delete E</button>
      </div>
    </div>
  </div>
</div>
<div id="option_f">
  <div class="control-group">
    <label class="control-label">F</label>

    <div class="controls">
      <%= f.text_area :item_f, :rows => 3 %>
      <%= f.check_box :key_f, {:id => "depot_keys_f"}, "F","" %>
    </div>
  </div>
  <div class="control-group" id="btn_con_f">
    <div class="controls">
      <div class="btn-group">
        <button class="btn" type="button" id="btn_add_g">Add G</button>
        <button class="btn" type="button" id="btn_del_f">delete F</button>
      </div>
    </div>
  </div>
</div>
<div id="option_g">
  <div class="control-group">
    <label class="control-label">G</label>

    <div class="controls">
      <%= f.text_area :item_g, :rows => 3 %>
      <%= f.check_box :key_g, {:id => "depot_keys_g"}, "G", "" %>
    </div>
  </div>
  <div class="control-group" id="btn_con_g">
    <div class="controls">
      <div class="btn-group">
        <button class="btn" type="button" id="btn_add_h">Add H</button>
        <button class="btn" type="button" id="btn_del_g">delete G</button>
      </div>
    </div>
  </div>
</div>
<div id="option_h">
  <div class="control-group">
    <label class="control-label">H</label>

    <div class="controls">
      <%= f.text_area :item_h, :rows => 3 %>
      <%= f.check_box :key_h, {:id => "depot_keys_h"}, "H", "" %>
    </div>
  </div>
  <div class="control-group" id="btn_con_h">
    <div class="controls">
      <div class="btn-group">
        <button class="btn" type="button" id="btn_add_i">Add I</button>
        <button class="btn" type="button" id="btn_del_h">delete H</button>
      </div>
    </div>
  </div>
</div>
<div id="option_i">
  <div class="control-group">
    <label class="control-label">I</label>

    <div class="controls">
      <%= f.text_area :item_i, :rows => 3 %>
      <%= f.check_box :key_i, {:id => "depot_keys_i"}, "I", "" %>
    </div>
  </div>
  <div class="control-group" id="btn_con_i">
    <div class="controls">
      <div class="btn-group">
        <button class="btn" type="button" id="btn_add_j">Add J</button>
        <button class="btn" type="button" id="btn_del_i">delete I</button>
      </div>
    </div>
  </div>
</div>
<div id="option_j">
  <div class="control-group" id="single_j">
    <label class="control-label">J</label>

    <div class="controls">
      <%= f.text_area :item_j, :rows => 3 %>
      <%= f.check_box :key_j, {:id => "depot_keys_j"}, "J", "" %>
    </div>
  </div>
  <div class="control-group" id="btn_con_j">
    <div class="controls">
      <div class="btn-group">
        <button class="btn" type="button" id="btn_del_j">delete J</button>
      </div>
    </div>
  </div>
</div>


<script type="text/javascript">
  $(document).ready(function () {
      $("[id^='btn_con_']").hide();

    if ($("#depot_item_b").val().length < 1) {
      $("#option_b").hide();
      $("#btn_con_a").show();
    }
    if ($("#depot_item_c").val().length < 1) {
      $("#option_c").hide();
      $("#btn_con_b").show();
    }
    if ($("#depot_item_d").val().length < 1) {
      $("#option_d").hide();
      $("#btn_con_c").show();
    }
    if ($("#depot_item_e").val().length < 1) {
      $("#option_e").hide();
      $("#btn_con_d").show();
    }
    if ($("#depot_item_f").val().length < 1) {
    $("#option_f").hide();
    $("#btn_con_e").show();
    }
    if ($("#depot_item_g").val().length < 1) {
      $("#option_g").hide();
      $("#btn_con_f").show();
    }
    if ($("#depot_item_h").val().length < 1) {
      $("#option_h").hide();
      $("#btn_con_g").show();
    }
    if ($("#depot_item_i").val().length < 1) {
      $("#option_i").hide();
      $("#btn_con_h").show();
    }
    if ($("#depot_item_j").val().length < 1) {
      $("#option_j").hide();
      $("btn_con_i").show();
    }
    $("#btn_add_b").on('click',function(){
      $("#btn_con_a").hide();
      $("#option_b").show(1000);
    });
    $("#btn_add_c").click(function(){
      $("#btn_con_b").hide();
      $("#option_c").show(1000);
    });
    $("#btn_add_d").click(function(){
      $("#btn_con_c").hide();
      $("#option_d").show(1000);
    });
    $("#btn_add_e").click(function(){
      $("#btn_con_d").hide();
      $("#option_e").show(1000);
    });
    $("#btn_add_f").click(function(){
      $("#btn_con_e").hide();
      $("#option_f").show(1000);
    });
    $("#btn_add_g").click(function(){
      $("#btn_con_f").hide();
      $("#option_g").show(1000);
    });
    $("#btn_add_h").click(function(){
      $("#btn_con_g").hide();
      $("#option_h").show(1000);
    });
    $("#btn_add_i").click(function(){
      $("#btn_con_h").hide();
      $("#option_i").show(1000);
    });
    $("#btn_add_j").click(function(){
      $("#btn_con_i").hide();
      $("#option_j").show(1000);
    });
    $("#btn_del_b").click(function(){
      $("#depot_keys_b").attr("checked", false);
      $("#depot_item_b").val("");
      $("#option_b").hide(500);
      $("#btn_con_a").show(500);
    });
    $("#btn_del_c").click(function(){
      $("#depot_keys_c").attr("checked", false);
      $("#depot_item_c").val("");
      $("#option_c").hide(500);
      $("#btn_con_b").show(500);
    });
    $("#btn_del_d").click(function(){
      $("#depot_keys_d").attr("checked", false);
      $("#depot_item_d").val("");
      $("#option_d").hide(500);
      $("#btn_con_c").show(500);
    });
    $("#btn_del_e").click(function(){
      $("#depot_keys_e").attr("checked", false);
      $("#depot_item_e").val("");
      $("#option_e").hide(500);
      $("#btn_con_d").show(500);
    });
    $("#btn_del_f").click(function(){
      $("#depot_keys_f").attr("checked", false);
      $("#depot_item_f").val("");
      $("#option_f").hide(500);
      $("#btn_con_e").show(500);
    });
    $("#btn_del_g").click(function(){
      $("#depot_keys_g").attr("checked", false);
      $("#depot_item_g").val("");
      $("#option_g").hide(500);
      $("#btn_con_f").show(500);
    });
    $("#btn_del_h").click(function(){
      $("#depot_keys_h").attr("checked", false);
      $("#depot_item_h").val("");
      $("#option_h").hide(500);
      $("#btn_con_g").show(500);
    });
    $("#btn_del_i").click(function(){
      $("#depot_keys_i").attr("checked", false);
      $("#depot_item_i").val("");
      $("#option_i").hide(500);
      $("#btn_con_h").show(500);
    });
    $("#btn_del_j").click(function(){
      $("#depot_keys_j").attr("checked", false);
      $("#depot_item_j").val("");
      $("#option_j").hide(500);
      $("#btn_con_i").show(500);
    });
  })

</script>

app/views/depots/_form.html.erb
<%= form_for(@depot) do |f| %>
  <% if @depot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@depot.errors.count, "error") %> prohibited this depot from being saved:</h2>

      <ul>
      <% @depot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/depots/_form_judge.html.erb
# encoding: utf-8
<div class="control-group">
  <label class="control-label">答案</label>
  <div class="controls"><div class="form-inline">
    <%= f.radio_button :keys, "T" %><label for="depot_keys_t">正确</label>
    <%= f.radio_button :keys, "L" %><label for="depot_keys_f">错误</label>
  </div>
</div>
</div>

app/views/depots/_navbar.html.erb
<% content_for :navbar do %>
  <ul class="nav">
    <li class="active"><a href="/depots"><i class="icon-home"></i> 题库</a></li>
    <li><%= link_to "新建题目", new_depot_path %></li>
    <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">分类列表<b class="caret"></b></a>
    <ul class="dropdown-menu">
      <% user_categories(current_user).each do |d| %>
        <li><%= link_to d[0], part_list_depot_path(d[1]), :remote => true %></li>
      <% end %>
    </ul>
    </li>
    <li><%= link_to "作业本", assignments_path %></li>
    <li><%= link_to "新建作业本", new_assignment_path %></li>
  </ul>
  <%= form_tag url_for(:controller => "depots", :action => "search"), :method => "get", :remote => true, :class => "navbar-search pull-right" do %>
    <input name="query" type="text" class="search-query span2" placeholder="查找关键字">
  <% end %>
<% end %>
<script type="text/javascript">
  $(document).ready(function(){
    $('.dropdown-toggle').dropdown();
  });
</script>

app/views/depots/edit.html.erb
# encoding: utf-8
<%= form_for @depot, :html => {:class => "form-horizontal"} do |f| %>
  <fieldset>
    <legend> 编辑 </legend>
    <div class="control-group">
      <label class="control-label" for="depot_category_id">分类</label>
      <div class="controls">
        <%= f.select :category_id, user_categories(current_user) %>
        <%= f.hidden_field :owner_id,:value => current_user.id %>
        <%= f.hidden_field :user_id, :value => current_user.id %>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="depot_title">题目</label>
      <div class="controls">
        <%= f.text_area :title, :rows => 5 %>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="depot_typies">类型</label>
      <div class="controls"><div class="form-inline">
        <%= f.radio_button :typies, "single" %> <label for="depot_typies_single">单选题</label>
        <%= f.radio_button :typies, "multiple" %> <label for="depot_typies_multiple">多选题</label>
        <%= f.radio_button :typies, "judgment" %> <label for="depot_typies_judgment">判断题</label>
      </div></div>
    </div>
    <div id="subform">
      <% if @depot.typies == "single" %>
      <%= render(:partial => "edit_single", :locals => {:f => f}, :object => @depot) %>
      <% elsif @depot.typies == "multiple" %>
      <%= render(:partial => "edit_multiple", :locals => {:f => f}) %>
      <%  elsif @depot.typies == "judgment" %>
      <%= render :partial => "edit_judge", :locals => {:f => f} %>
    <% end %>
    </div>
    <script type="text/javascript">
      $(document).ready(function () {
        $("#depot_typies_single").click(function () {
          $("#subform").html("<%=j render(:partial => "edit_single", :locals => {:f => f}) %>").hide().show(500);
        });
        $("#depot_typies_multiple").click(function () {
          $("#subform").html("<%=j render(:partial => "edit_multiple", :locals =>{:f => f}) %>").hide().show(500);
        });
        $("#depot_typies_judgment").click(function () {
          $("#subform").html("<%=j render(:partial => "edit_judge", :locals => {:f => f}) %>").hide().show(500);
        });
      });
    </script>
    <div class="control-group">
      <label class="control-label" for="depot_readspeed">读题速度</label>
      <div class="controls">
        <%= f.select :readspeed, read_speed %>
      </div>
    </div>
    <div class="control-group">
      <div class="controls">
        <%= f.submit "update", :class => "btn" %>
      </div>
    </div>
  </fieldset>
<% end %>

app/views/depots/index.html.erb
<%= render 'navbar' %>
<h3>题库列表</h3>


<% @depots.each do |depot| %>
  <div class="media">
    <div class="media-body">
      <h4 class="media-heading"><%= depot.category.title %></h4>
      <div class="media">
        <%= depot.title %>
      </div>
    </div>
  </div>
    <%= link_to '查看', depot %>
    <%= link_to '编辑', edit_depot_path(depot) %>
    <%= link_to '删除', depot, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

<br />

<%= link_to 'New Depot', new_depot_path %>

app/views/depots/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="span2">分类</div>
  <div class="span6">
    <%= @depot.category.title %>
  </div>
</div>
<div class="row">
  <div class="span2">标题</div>
  <div class="span6">
    <%= @depot.title %>
  </div>
</div>
<% if @depot.item_a?  %>
  <div class="row">
    <div class="span2">A</div>
    <div class="span6">
      <%= @depot.item_a %>
    </div>
  </div>
<% end %>
<% if @depot.item_b?  %>
  <div class="row">
    <div class="span2">B</div>
    <div class="span6">
      <%= @depot.item_b %>
    </div>
  </div>
<% end %>
<% if @depot.item_c? %>
  <div class="row">
    <div class="span2">C</div>
    <div class="span6">
      <%= @depot.item_c %>
    </div>
  </div>
<% end %>
<% if @depot.item_d?  %>
  <div class="row">
    <div class="span2">D</div>
    <div class="span6">
      <%= @depot.item_d %>
    </div>
  </div>
<% end %>
<% if @depot.item_e? %>
  <div class="row">
    <div class="span2">E</div>
    <div class="span6">
      <%= @depot.item_e %>
    </div>
  </div>
<% end %>
<% if @depot.item_f? %>
  <div class="row">
    <div class="span2">F</div>
    <div class="span6">
      <%= @depot.item_f %>
    </div>
  </div>
<% end %>
<% if @depot.item_g? %>
  <div class="row">
    <div class="span2">G</div>
    <div class="span6">
      <%= @depot.item_g %>
    </div>
  </div>
<% end %>
<% if @depot.item_h? %>
  <div class="row">
    <div class="span2">H</div>
    <div class="span6">
      <%= @depot.item_h %>
    </div>
  </div>
<% end %>
<% if @depot.item_i? %>
  <div class="row">
    <div class="span2">I</div>
    <div class="span6">
      <%= @depot.item_i %>
    </div>
  </div>
<% end %>
<% if @depot.item_j? %>
  <div class="row">
    <div class="span2">J</div>
    <div class="span6">
      <%= @depot.item_j %>
    </div>
  </div>
<% end %>
<%= link_to 'Edit', edit_depot_path(@depot) %> |
<%= link_to 'Back', depots_path %>