config/routes.rb
Do::Application.routes.draw do
  resources :homeworks
  resources :messages

  resources :assignments do
    get :assign, :on => :member 
    get :puto, :on => :member
    get :already, :on => :member
    get :putout, :on => :member
  end
  resources :depots do
    get :part_list, :on => :member
  end
  resources :categories

  controller :sessions do
    get 'login' => :new
    root :to => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  get '/register' => "users#new"
  get 'registered' => "users#registered"
  match 'user_info' => "users#info"
  get 'user_act' => "users#user_act"
  resources :users
  match 'circles/search' => 'circles#search'
  match 'depots/search' => 'depots#search'
  match 'circles_join_me' => 'circles#join_me'
  match 'add_friend' => 'circles#add_friend'
  resources :circles do
    get :part_list, :on => :member
  end

end

app/models/circle.rb
class Circle < ActiveRecord::Base
  attr_accessible :title, :user_id
  validates_presence_of :title
  belongs_to :master, :class_name => 'User', :foreign_key => "user_id"
  belongs_to :friend, :class_name => 'User', :foreign_key => "friend_id"
end

app/controllers/circles_controller.rb
# encoding: utf-8
class CirclesController < ApplicationController
  def index
    @messages = Message.find_all_by_to_id(current_user.id)
    @circles_group = current_user.master.all
  end
  def new
    @circle = Circle.new
    respond_to do |format|
      format.js
    end
  end
  def create
    @circle = Circle.new(params[:circle])
    @circle.save
    redirect_to :action => :index
  end

  def search
    q_name = params[:query].split.map {|term| "%#{term}%"}
    q_email = params[:query]
    @users= User.where("name like ? or email = ?", q_name,q_email )
    respond_to do |format|
      format.js
    end
  end

  def join_me
    p=params[:user_id]
    circle = Circle.where("user_id = ? and friend_id = ?", current_user.id, p.to_i)
    if circle.blank?
      message = Message.new()
      message.from_id = current_user.id
      message.typies = "join_me"
      message.to_id = p.to_i
      message.message = "join me a friend!"
      message.save
    end
    respond_to do |format|
      format.js
    end
  end
  def add_friend
    @message = Message.find(params[:m])
    c = Circle.where(["user_id = ? and friend_id = ?", @message.to_id.to_i,@message.from_id.to_i])
    if c.blank?
      circle = Circle.new
      circle.user_id = @message.to_id
      circle.friend_id = @message.from_id
      circle.title = "未分组"
      circle.save
      @message.delete
    else
      render :text => "yes"
    end
    respond_to do |format|
      format.js
    end
  end
  def part_list
    @title = params[:id]
    @lists = Circle.where(["user_id = ? and title = ?", current_user.id, @title])
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/circles_helper.rb
module CirclesHelper
  def user_circles_count
    count = current_user.master.all.count 
    if count < 1
      count = 0
    end
    count
  end
  def user_circles_titles
    titles = current_user.master.map {|m| m.title}
  end
end

app/views/circles/_navbar.html.erb
<% content_for :navbar do %>
    <ul class="nav">
      <li class="active"><a href="#"><i class="icon-home"></i> 圈子<%= user_circles_count %></a></li>
      <li><%= link_to "新建", new_circle_path, :remote => true %> </li>
      <li><a href="#">Link</a></li>
      <li><a href="#">Link</a></li>
      <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown"> 所有圈子 <b class="caret"></b></a>
      <ul class="dropdown-menu">
        <% user_circles_titles.each do |t| %>
          <li><%= link_to t, part_list_circle_path(t), :remote => true %></li>
        <% end %>
      </ul>
      </li>
    </ul>
    <%= form_tag url_for(:controller => "circles", :action =>"search"),:method => "get",:remote=>true, :class => "navbar-search pull-right" do %>
      <input name="query" type="text" class="search-query span2" placeholder="找人">
    <% end %>
<% end %>
<script type="text/javascript">
  $(document).ready( function() {
      $('.dropdown-toggle').dropdown();
      } );
</script>

app/views/circles/_new.html.erb
new circle
<%= form_for @circle, :url => {:controller => 'circles', :action => 'create'},:html => {:class => "form-inline"} do |f| %>
  <%= f.label :title, "圈子命名：" %>
  <%= f.text_field :title %>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <%= f.submit "创建", :class => "btn" %>
<% end %>

app/views/circles/_search.html.erb
<%= render :partial => "navbar" %>
<ul class="thumbnails">
  <% @user.each do |user| %>
    <li class="span3" id="join_me">
    <%= user_face(user) %>
    <div class="caption">
      <h5><%= user.name %></h5>
      <%= link_to "info", user_info_url(user_id: user.id ), class: 'btn' if user.master.map{|m| m.friend_id}.include?current_user.id %> 
        <%= button_to "add_friend", circles_join_me_path(user_id: user.id),:class => "btn btn-success", :remote => true unless user.master.map{|m| m.friend_id}.include?current_user.id %>
    </div>
    </li>
  <% end %>
</ul>

app/views/circles/_user_list.html.erb
<ul class = "media-list">
  <li class = "media">
  <a class = "pull-left" href="#">
    <%= user_face(user) %>
  </a>
  <div class="media-body">
    <h4 class="media-heading"><%= user.name %></h4>
    <div class="media">aaaaaaaaaaa
      
    </div>
  </div>
  </li>
</ul>

app/views/circles/_users_list.html.erb
iab
<% lists.each do |u| %>
  <%= u.title %>
<% end %>

app/views/circles/index.html.erb
<%= render :partial => "navbar" %>
<div id="create"></div>
<div id="search"></div>
<div id="circle_list"></div>
<% @messages.each do |m| %>
   <%= m.title %>
<% end %>
<% @circles_group.each do |cg| %>
  <%= cg.title %>
<% end %>

app/views/circles/join_me.js.erb
$('#join_me').html("信息已发至").hide(200).show(800)

app/views/circles/new.js.erb
$("#create").html("<%=j render 'new' %>");

app/views/circles/part_list.js.erb
$("#circle_list").html("<%=j render :partial => 'users_list', :locals => { :lists => @lists } %>")

app/views/circles/search.html.erb
<%= render :partial => "navbar" %>
<ul class="thumbnails">
  <% @user.each do |user| %>
    <li class="span3" id="join_me">
    <%= user_face(user) %>
    <div class="caption">
      <h5><%= user.name %></h5>
        <%= link_to "info", user_info_url(user_id: user.id ), class: 'btn' %> 
        <%= button_to "add_friend", circles_join_me_path(user_id: user.id),:class => "btn btn-success", :remote => true %>
    </div>
    </li>
  <% end %>
</ul>

app/views/circles/search.js.erb
<% if @users.length > 0 %>
    $("#search").html("<h3>列表</h3>")
  <% @users.each do |u| %>
    $("#search").append("<%=j render :partial => 'user_list', :locals => {:user => u} %>")
  <% end %>
<% else %>
$("#search").html("没找到任何人！")
<% end %>